---

- name: Ensure Radarr paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ radarr_uid }}"
    group: "{{ radarr_gid }}"
  with_items:
    - "{{ radarr_base_path }}"
    - "{{ radarr_data_path }}"

- name: Ensure Radarr support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ radarr_base_path }}/{{ item }}"
    owner: "{{ radarr_uid }}"
    group: "{{ radarr_gid }}"
    mode: "0640"
  with_items:
    - env
    - labels

- name: Ensure Radarr container image is pulled
  community.docker.docker_image:
    name: "{{ radarr_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ radarr_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else radarr_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Radarr container network is created
  community.general.docker_network:
    name: "{{ radarr_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Radarr systemd installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/radarr.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ radarr_identifier }}.service"
    mode: "0644"
