---

- name: Check existence of Radarr systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ radarr_identifier }}.service"
  register: radarr_service_stat

- name: Uninstall Radarr systemd services and files
  when: radarr_service_stat.stat.exists | bool
  block:
    - name: Ensure Radarr systemd service is stopped
      ansible.builtin.service:
        name: "{{ radarr_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Radarr systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ radarr_identifier }}.service"
        state: absent

    - name: Ensure Radarr path doesn't exist
      ansible.builtin.file:
        path: "{{ radarr_base_path }}"
        state: absent
