---

- name: Fail if required Radarr settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] | length == 0"
  with_items:
    - radarr_uid
    - radarr_gid
    - radarr_hostname

- name: Fail if Radarr architecture is not supported
  ansible.builtin.fail:
    msg: >
      Your configuration specifies a CPU architecture (`{{ radarr_arch }}`) which is not currently supported.
      This Radarr role also does not support self-building yet, so it's not possible to make use of it.
  when: "radarr_arch not in ['amd64', 'arm64']"

- name: Validate Radarr Traefik configuration
  when: radarr_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Radarr Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - radarr_container_labels_traefik_hostname
        - radarr_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `radarr_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if radarr_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          radarr_container_labels_traefik_path_prefix (`{{ radarr_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/radarr`).
      when: "radarr_container_labels_traefik_path_prefix != '/' and radarr_container_labels_traefik_path_prefix[-1] == '/'"
